name: Create Pull Request to sync with Wikimeda Repository Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: update-REL1_39-${{ format('{0:yyyyMMdd}', github.event.schedule) }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: REL1_39
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    - name: Show Git Config
      run: |
        git config --local --list

    - name: Configure Upstream
      run: |
        git remote add upstream https://github.com/wikimedia/mediawiki.git
        git fetch upstream REL1_39

    - name: Create New Branch
      run: |
        git checkout -b ${{ env.BRANCH_NAME }}
        git merge upstream/REL1_39

    - name: Push Changes
      run: |
        git push origin ${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
        title: "Update REL1_39 from Upstream"
        body: "This PR is to merge the latest changes from the upstream REL1_39 branch."
        labels: |
          auto
          update
          automerge
